app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group([
    //'domain'     => Config::get('app.domain'),
    'namespace'  => 'Admin',
    'as'         => 'admin.',
    'middleware' => [
        'auth.joomla',
        //'admin.auth',
        'ACL',
    ],
    'prefix'     => 'admin'
], function () {
    Route::resource('roadmaps', 'RoadmapsController', [
        'names' => [
            'index'   => 'roadmaps.index',
            'create'  => 'roadmaps.create',
            'store'   => 'roadmaps.store',
            'show'    => 'roadmaps.show',
            'edit'    => 'roadmaps.edit',
            'update'  => 'roadmaps.update',
            'destroy' => 'roadmaps.destroy',
        ]
    ]);

    Route::group(['prefix' => 'roadmaps', 'as' => 'roadmaps.'], function () {
        Route::resource('{roadmaps}/modules', 'ModuleRoadmapController', [
            'except' => ['show', 'create', 'store'],
            'names'  => [
                'index'   => 'modules.index',
                'edit'    => 'modules.edit',
                'update'  => 'modules.update',
                'destroy' => 'modules.destroy',
            ]
        ]);
    });

    Route::resource('modules', 'ModulesController', [
        'only'  => ['index', 'show', 'create', 'store'],
        'names' => [
            'index'  => 'modules.index',
            'show'   => 'modules.show',
            'create' => 'modules.create',
            'store'  => 'modules.store',
        ],
    ]);

    Route::group(['middleware' => ['admin.module.modify']], function () {
        Route::resource('modules', 'ModulesController', [
            'only'  => ['edit', 'update'],
            'names' => [
                'edit'   => 'modules.edit',
                'update' => 'modules.update',
            ],
        ]);
    });

    Route::delete('modules/{modules}', [
        'middleware' => ['admin.module.destroy'],
        'as'         => 'modules.destroy',
        'uses'       => 'ModulesController@destroy'
    ]);

    Route::group(['prefix' => 'modules', 'as' => 'modules.'], function () {
        Route::group(['middleware' => ['admin.module.modify']], function () {
            Route::resource('{modules}/lessons', 'LessonModuleController', [
                'only'  => ['create', 'store'],
                'names' => [
                    'create' => 'lessons.create',
                    'store'  => 'lessons.store',
                ],
            ]);
        });

        Route::group(['middleware' => ['admin.lesson.modify']], function () {
            Route::resource('{modules}/lessons', 'LessonModuleController', [
                'only'  => ['edit', 'update'],
                'names' => [
                    'edit'   => 'lessons.edit',
                    'update' => 'lessons.update',
                ],
            ]);
        });

        Route::resource('{modules}/lessons', 'LessonModuleController', [
            'only'  => ['index', 'show'],
            'names' => [
                'index' => 'lessons.index',
                'show'  => 'lessons.show',
            ],
        ]);

        Route::group(['middleware' => ['admin.lesson.destroy']], function () {
            Route::resource('{modules}/lessons', 'LessonModuleController', [
                'only'  => ['destroy'],
                'names' => [
                    'destroy' => 'lessons.destroy',
                ],
            ]);
        });
    });

    Route::resource('lessons', 'LessonsController', [
        'only'  => ['index', 'show', 'create', 'store'],
        'names' => [
            'index'  => 'lessons.index',
            'show'   => 'lessons.show',
            'create' => 'lessons.create',
            'store'  => 'lessons.store',
        ],
    ]);

    Route::group(['middleware' => ['admin.lesson.modify']], function () {
        Route::resource('lessons', 'LessonsController', [
            'only'  => ['edit', 'update'],
            'names' => [
                'edit'   => 'lessons.edit',
                'update' => 'lessons.update',
            ],
        ]);
    });

    Route::delete('lessons/{lessons}', [
        'middleware' => ['admin.lesson.destroy'],
        'as'         => 'lessons.destroy',
        'uses'       => 'LessonsController@destroy'
    ]);

    Route::resource('resources', 'ResourcesController', [
        'names' => [
            'index'   => 'resources.index',
            'create'  => 'resources.create',
            'store'   => 'resources.store',
            'show'    => 'resources.show',
            'edit'    => 'resources.edit',
            'update'  => 'resources.update',
            'destroy' => 'resources.destroy',
        ]
    ]);
    Route::post('resources/upload', [
        'as'   => 'resources.upload',
        'uses' => 'ResourcesController@upload'
    ]);

    Route::resource('tags', 'TagsController', [
        'names' => [
            'index'   => 'tags.index',
            'create'  => 'tags.create',
            'store'   => 'tags.store',
            'show'    => 'tags.show',
            'edit'    => 'tags.edit',
            'update'  => 'tags.update',
            'destroy' => 'tags.destroy',
        ]
    ]);

    Route::get('/', ['as' => 'home.index', 'uses' => 'HomeController@index']);
});

Route::group([
    'middleware' => [
        //'auth.joomla',
        //'app.auth',
        //'ACL'
    ],
], function () {
    Route::get('', [
        'uses' => 'RoadmapsController@index'
    ]);

    Route::resource('roadmaps', 'RoadmapsController', [
        'only'  => ['index', 'show'],
        'names' => [
            'index' => 'roadmaps.index',
            'show'  => 'roadmaps.show',
        ]
    ]);
    Route::group(['prefix' => 'roadmaps', 'as' => 'roadmaps.'], function () {
        Route::resource('{roadmaps}/lessons', 'Roadmaps\LessonsController', [
            'only'  => ['index', 'show'],
            'names' => [
                'index' => 'lessons.index',
                'show'  => 'lessons.show',
            ]
        ]);

        Route::post('{roadmaps}/lessons/{lessons}/complete',
            ['as' => 'lessons.complete', 'uses' => 'Roadmaps\LessonsController@complete']);
        Route::post('{roadmaps}/lessons/{lessons}/share',
            ['as' => 'lessons.share', 'uses' => 'Roadmaps\LessonsController@share']);
    });

    Route::resource('tags', 'TagsController', [
        'only'  => ['index', 'show'],
        'names' => [
            'index' => 'tags.index',
            'show'  => 'tags.show',
        ]
    ]);

    Route::resource('modules', 'ModulesController', [
        'only'  => ['index'],
        'names' => [
            'index' => 'modules.index'
        ]
    ]);
    Route::resource('lessons', 'LessonsController', [
        'only'  => ['index', 'show'],
        'names' => [
            'index' => 'lessons.index',
            'show' => 'lessons.show'
        ]
    ]);
    Route::resource('resources', 'ResourcesController', [
        'only'  => ['index'],
        'names' => [
            'index' => 'resources.index'
        ]
    ]);
});

app/Http/Controllers/Admin/LessonsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Tag;
use App\Models\User;
use App\Models\Author;
use App\Models\Lesson;
use App\Models\Module;
use App\Models\Resource;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\LessonStoreRequest;
use App\Http\Requests\Admin\LessonUpdateRequest;

class LessonsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function index()
    {
        /*$lessons = Lesson::with([
            'author.user',
            'tags',
            'resources',
        ])->orderBy('bonus')->orderBy('order')->orderBy('created_at', 'DESC')->paginate();*/
        $lessons = Lesson::with([
            'author.user',
            'tags',
            'resources',
        ])->orderBy('bonus')->orderBy('order')->orderBy('created_at', 'DESC')->get();
        return \View::make('admin.lessons.index', compact('module', 'lessons'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $lesson = new Lesson();

        $authors = Author::get()->lists('name', 'uuid');
        $selected_author = null;

        $modules = Module::get()->lists('title', 'slug');
        $selected_module = null;

        $tags = Tag::get()->lists('name', 'slug');
        $selected_tags = [];

        $resources          = Resource::get();
        $select_resources = [];
        foreach ($resources as $resource) {
            $select_resources[$resource->slug] = "({$resource->type})\t{$resource->title}";
        }
        $resources = $select_resources;
        $selected_resources = [];

        $types = Lesson::types();
        $selected_type = null;

        return \View::make('admin.lessons.create',
            compact('lesson', 'authors', 'selected_author', 'modules', 'selected_module', 'tags', 'selected_tags', 'resources',
                'selected_resources', 'types', 'selected_type'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param LessonStoreRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(LessonStoreRequest $request)
    {
        $lesson = new Lesson($request->all());

        $user = \Auth::user();
        if ($user->isAdmin()) {
            $author = User::whereUuid($request->author)->first()->author;
        } else {
            $author = $user->author;
        }

        $module = Module::whereSlug($request->get('module'))->first();

        $lesson->author()->associate($author);
        $lesson->module()->associate($module);
        $lesson->save();
        $lesson->tags()->sync(Tag::whereIn('slug', $request->get('tags'))->get());
        $lesson->resources()->sync(Resource::whereIn('slug', $request->get('resources'))->get());

        return \Redirect::route('admin.lessons.index');
    }

    /**
     * Display the specified resource.
     *
     * @param Lesson $lesson
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function show(Lesson $lesson)
    {
        return \View::make('admin.lessons.show', compact('lesson'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Lesson $lesson
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Lesson $lesson)
    {
        $authors = Author::get()->lists('name', 'uuid');
        $selected_author = $lesson->author->uuid;

        $modules = Module::get()->lists('title', 'slug');
        $selected_module = $lesson->module->slug;

        $tags = Tag::get()->lists('name', 'slug');
        $selected_tags = $lesson->tags->pluck('slug')->toArray();

        $resources          = Resource::get();
        $select_resources = [];
        foreach ($resources as $resource) {
            $select_resources[$resource->slug] = "({$resource->type})\t{$resource->title}";
        }
        $resources = $select_resources;
        $selected_resources = $lesson->resources->pluck('slug')->toArray();

        $types = Lesson::types();
        $selected_type = null;

        return \View::make('admin.lessons.edit',
            compact('lesson', 'authors', 'selected_author', 'modules', 'selected_module', 'tags', 'selected_tags', 'resources',
                'selected_resources', 'types', 'selected_type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param LessonUpdateRequest $request
     * @param Lesson                    $lesson
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(LessonUpdateRequest $request, Lesson $lesson)
    {
        $lesson->fill($request->all());

        if (\Auth::user()->isAdmin()) {
            $author = User::whereUuid($request->author)->first()->author;
            $lesson->author()->associate($author);
        }

        $module = Module::whereSlug($request->get('module'))->first();

        $lesson->tags()->sync(Tag::whereIn('slug', $request->get('tags'))->get());
        $lesson->module()->associate($module);
        $lesson->resources()->sync(Resource::whereIn('slug', $request->get('resources'))->get());
        $lesson->save();

        return \Redirect::route('admin.lessons.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Lesson $lesson
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Lesson $lesson)
    {
        $lesson->delete();

        return \Redirect::route('admin.lessons.index');
    }
}

app/Http/Controllers/Admin/ModulesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use App\Models\Author;
use App\Models\Module;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\ModuleStoreRequest;
use App\Http\Requests\Admin\ModuleUpdateRequest;

class ModulesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function index()
    {
        //$modules = Module::with(['authors.user', 'author.user', 'lessons'])->orderBy('created_at', 'desc')->paginate();
        $modules = Module::with(['authors.user', 'author.user', 'lessons'])->orderBy('created_at', 'desc')->get();
        
        return \View::make('admin.modules.index', compact('roadmap', 'modules'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $module = new Module();

        $authors          = Author::get()->lists('name', 'uuid');
        $selected_author  = null;
        $selected_authors = [];
        $leaders          = Module::getAvailableLeaders()->lists('name', 'joomla_user_id');
        $selected_leader  = null;

        return \View::make('admin.modules.create',
            compact('module', 'authors', 'selected_author', 'selected_authors', 'leaders', 'selected_leader'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ModuleStoreRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ModuleStoreRequest $request)
    {
        $module = new Module($request->all());

        $user = \Auth::user();
        if ($user->isAdmin()) {
            $author = User::whereUuid($request->author)->first()->author;
        } else {
            $author = $user->author;
        }

        $module->author()->associate($author);
        $module->save();
        $module->authors()->sync(User::whereIn('uuid', $request->get('authors'))->get());

        return \Redirect::route('admin.modules.index');
    }

    /**
     * Display the specified resource.
     *
     * @param Module $module
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function show(Module $module)
    {
        
        return \Redirect::route('admin.modules.lessons.index', compact('module'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Module $module
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Module $module)
    {
        $authors          = Author::get();
        $authors          = array_combine($authors->pluck('uuid')->toArray(), $authors->pluck('name')->toArray());
        $selected_author  = $module->author->uuid;
        $selected_authors = $module->authors->pluck('uuid')->toArray();

        // Todo: Get leaders correctly
        $leaders         = Module::getAvailableLeaders()->lists('name', 'joomla_user_id');
        $selected_leader = null;

        return \View::make('admin.modules.edit',
            compact('module', 'authors', 'selected_author', 'selected_authors', 'leaders', 'selected_leader'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ModuleUpdateRequest $request
     * @param Module              $module
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(ModuleUpdateRequest $request, Module $module)
    {
        $module->fill($request->all());

        if (\Auth::user()->isAdmin()) {
            $author = User::whereUuid($request->author)->first()->author;
            $module->author()->associate($author);
        }

        $module->save();
        $module->authors()->sync(User::whereIn('uuid', $request->get('authors'))->get());

        return \Redirect::route('admin.modules.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Module $module
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Module $module)
    {
        $module->delete();

        return \Redirect::route('admin.modules.index');
    }
}

app/Http/Controllers/LessonsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Lesson;

class LessonsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lessons = Lesson::with(['module', 'module.roadmaps'])->get();

        return \View::make('lessons.index', compact('lessons'));
    }

}

resources/views/admin/modules/lessons/create.blade.php
@extends('admin.modules.lessons.layout')
@section('head')
    @include('admin.modules.lessons.includes.head')
@endsection

@section('body')

@include('admin.includes.sidebar')
    <!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">

        <h3>New lesson</h3>
        <p></p>
        <br>
        @include('admin.modules.lessons.form', ['route_name' => 'admin.modules.lessons.store', 'method' => 'POST'])
    </section>
</div>
@endsection

resources/views/admin/modules/lessons/edit.blade.php
@extends('admin.modules.lessons.layout')
@section('head')
    @include('admin.modules.lessons.includes.head')
@endsection

@section('body')

@include('admin.includes.sidebar')
    <!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h3>Edit lesson</h3>
        <p></p>
        <br>
        @include('admin.modules.lessons.form', ['route_name' => 'admin.modules.lessons.update', 'method' => 'PUT'])
    </section>

    <div class="modal fade modal-dialog-center" id="modal-remove" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content-wrap">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">
                            By deleting this lesson, every record of every
                            principal that completed it, will be deleted as well.
                        </h4>
                    </div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete this lesson?</p>
                    </div>
                    <div class="modal-footer">
                        {!! Form::open(['route' => ['admin.modules.lessons.destroy', $module, $lesson] ,'method'=>'DELETE', 'data-pjax' => '']) !!}
                        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                        <button type="submit" class="btn btn-danger">Yes</button>{!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/modules/lessons/form.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<style>
    .bar {
        height: 18px;
        background: green;
    }
</style>

{!! Form::model($lesson, ['method' => $method, 'route' => [$route_name, $module, $lesson], 'data-pjax' => '']) !!}
<div id="" class="box box-primary collapse in">
    <div class="box-body">
        @if(\Auth::user()->isAdmin())
            <div class="form-group">
                {!! Form::label('author', 'Author in charge') !!}
                {!! Form::select('author', $authors, $selected_author, [
                    'placeholder' => trans('lesson.fields.placeholders.author'),
                    'class' => 'form-control select2'
                ]) !!}
            </div>
        @endif
        <div class="form-group">
            {!! Form::label('title') !!}
            {!! Form::text('title', null, ['placeholder' => trans('lesson.fields.placeholders.title'), 'class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('description') !!}
            {!! Form::textarea('description', null, ['placeholder' => trans('lesson.fields.placeholders.description'), 'class' => 'form-control']) !!}
        </div>
{{--    <div class="form-group">
            {!! Form::label('image_url') !!}
            {!! Form::text('image_url', null, ['placeholder' => trans('lesson.fields.placeholders.image_url'), 'class' => 'form-control']) !!}
        </div> --}}
        <div class="form-group">
            {!! Form::label('order') !!}
            <!--{!! Form::selectRange('order', 1, 100, null, ['class' => 'form-control']) !!}-->
            {!! Form::text('order', null, ['placeholder' => '1', 'class' => 'form-control']) !!}

        </div>
        <div class="form-group">
            {!! Form::checkbox('bonus', 1, null, ['class' => 'checkbox-inline']) !!}
            {!! Form::label('bonus', 'Bonus lesson (means optional)') !!}
        </div>
        <div class="form-group">
            {!! Form::label('content') !!}
            {!! Form::textarea('content', null, ['placeholder' => trans('lesson.fields.placeholders.content'), 'class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('type') !!}
            {!! Form::select('type', $types, $selected_type, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('ect', 'Estimated completion time (in minutes)') !!}
            <!--{!! Form::selectRange('ect', 1, 1000, null, ['class' => 'form-control']) !!}-->
            {!! Form::text('ect', null, ['placeholder' => '1', 'class' => 'form-control']) !!}

        </div>
            <div class="form-group">
                {!! Form::label('Link for "Ask a Question" button') !!}
                {!! Form::text('ask_a_question_link', null, ['placeholder' => trans('lesson.fields.placeholders.ask_a_question_link'), 'class' => 'form-control']) !!}
            </div>
        <div class="form-group">
            {!! Form::label('tags') !!}
            {!! Form::select('tags[]', $tags, $selected_tags, [
                'placeholder' => trans('lesson.fields.placeholder.tags'),
                'id' => 'tags',
                'class' => 'form-control select2',
                'multiple' => ''
            ]) !!}
        </div>
        <div class="form-group">
            {!! Form::label('Resources') !!}
            {!! Form::select('resources[]', $resources, $selected_resources, [
                'placeholder' => trans('lesson.fields.placeholder.resources'),
                'id' => 'resources',
                'class' => 'form-control select2',
                'multiple' => ''
            ]) !!}
        </div>
    </div>

    <div class="box-footer text-right">
        {!! Html::linkRoute('admin.modules.lessons.index', 'Back to list', [$module], ['class' => 'btn btn-default pjax-requester']) !!}
        {!! Form::submit('Save', ['class' => 'btn btn-success', 'data-pjax' => '']) !!}
        @if ($route_name === 'admin.modules.lessons.update')
            {!! Html::link('#', 'Delete', ['class' => 'btn btn-danger pjax-requester', 'data-toggle' => 'modal', 'data-target' => '#modal-remove']) !!}
        @endif
    </div>
</div>
{!! Form::close() !!}
{!! Form::open(['route' => 'admin.resources.upload','class'=>'upload-form']) !!}
    <div>
        <span class="btn btn-success fileinput-button">
            <i class="fa fa-plus"></i>
            <span>Select files...</span>
            {!! Form::file('resource-file', ['id' => 'fileupload', 'multiple' => '']) !!}
        </span>
    </div>
{!! Form::close() !!}

<div>
    &nbsp;
</div>
<div id="progress" class="progress hidden">
    <div class="progress-bar progress-bar-success"></div>
</div>

<div class="modal fade" id="mediaModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Select resource</h4>
            </div>
            <div class="modal-body">
                <div class="res">
                    <input type="checkbox" name="idFileX">
                    &nbsp;<span> Something.pdf</span>
                </div>
                <div class="res">
                    <input type="checkbox" name="idFileX">
                    &nbsp;<span> Something.pdf</span>
                </div>
                <div class="res">
                    <input type="checkbox" name="idFileX">
                    &nbsp;<span> Something.pdf</span>
                </div>
            </div>
            <div class="modal-body">
                <button type="button" class="btn btn-primary">Upload New Resource</button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div><!-- /.modal -->

resources/views/admin/modules/lessons/index.blade.php
@extends('admin.modules.lessons.layout')

@section('body')

@include('admin.includes.sidebar')
    <!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">

        <h3>Lessons for module "{{ $module->title }}"</h3>
        <p>{{ $module->description }}</p>
        <br>

        <div class="box box-primary collapse in" >
            <div class="box-header">
                <div>
                    <a href="{{ URL::route('admin.modules.index') }}" class="btn btn-app">
                        <i class="fa fa-mail-reply"></i> Back to list
                    </a>
                    @can('modify', $module)
                    <a href="{{ URL::route('admin.modules.lessons.create', $module) }}" class="btn btn-app pjax-requester">
                        <i class="fa fa-plus"></i> New lesson
                    </a>
                    @endcan
                </div>
            </div>
            <div class="box-body">
                @include('admin.modules.lessons.table')
            </div>
        </div>
    </section>
</div>
@endsection

resources/views/admin/modules/lessons/layout.blade.php
@extends('admin.layout')
@section('head')
    @include('admin.lessons.includes.head')
@endsection
@section('footer-specific')
    @include('admin.modules.lessons.includes.footer')
@endsection

resources/views/admin/modules/lessons/show.blade.php
@extends('admin.modules.lessons.layout')


@section('body')

@include('admin.includes.sidebar')
    <!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h3>Lesson</h3>
        <br>
        <div class="box box-primary collapse in" >
            <div class="box-header with-border">
                <h3 class="box-title">{{ $lesson->title }}</h3>
            </div>
            <div >
                <!-- form start -->
                <div class="box-body">
                    <p class="text-left"><i>{{ $lesson->description }}</i></p>
                    <div>
                        {!! $lesson->content !!}
                    </div>
                    {!! Html::linkRoute('admin.modules.lessons.index', 'Back to list', [$lesson->module, $lesson], ['class' => 'btn btn-default pjax-requester']) !!}
                </div><!-- /.box-body -->
            </div>
        </div>
    </section>
</div>
@endsection

resources/views/admin/modules/lessons/table.blade.php
<table id="lessons" class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>Title</th>
        <th>In charge of</th>
        <th>Image</th>
        <th>Type</th>
        <th>Tags</th>
        <th>Number of resources</th>
        <th>Order</th>
        <th>Is bonus content</th>
        <th width="90">Action</th>
    </tr>
    </thead>
    <tbody>

    @forelse($lessons as $lesson)
        <tr>
            <td>{{ $lesson->title }}</td>
            <td>{{ $lesson->author->name }}</td>
            <td>{{ $lesson->image_url }}</td>
            <td>{{ ucfirst($lesson->type) }}</td>
            <td>
                <b>{{ $lesson->tags->count() }}</b>:
                {{ $lesson->getTagsNamesText() }}</td>
            <td>{{ $lesson->resources->count() }}</td>
            <td>{{ $lesson->order }}</td>
            <td>{{ $lesson->bonus? 'Yes': 'No' }}</td>
            <td class="action">
                <a href="{{ URL::route('admin.modules.lessons.show', [$module, $lesson]) }}" title="Show lesson details" class="pjax-requester">
                    <span class="fa fa-eye" aria-hidden="true"></span>
                </a>
                @can('modify', $lesson)
                <a href="{{ URL::route('admin.modules.lessons.edit', [$module, $lesson]) }}" title="Edit lesson" class="pjax-requester">
                    <span class="fa  fa-edit" aria-hidden="true"></span>
                </a>
                @endcan
                @can('destroy', $lesson)
                {!! Form::open(['route' => ['admin.modules.lessons.destroy', $module, $lesson] ,'method'=>'DELETE','class'=>'del-form', 'data-pjax' => '']) !!}
                {!! Form::submit('X', ['class' => 'btn-remove link', 'title' => 'Delete lesson', 'aria-hidden' => 'true']) !!}
                {!! Form::close() !!}
                @endcan
            </td>
        </tr>
    @empty
        <p class="text-center"><i>There are no lessons set for this module</i></p>
    @endforelse
    </tbody>
</table>

{{-- $lessons->render(new App\Pagination\AdminLTETwoPresenter($lessons)) --}}