app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group([
    //'domain'     => Config::get('app.domain'),
    'namespace'  => 'Admin',
    'as'         => 'admin.',
    'middleware' => [
        'auth.joomla',
        //'admin.auth',
        'ACL',
    ],
    'prefix'     => 'admin'
], function () {
    Route::resource('roadmaps', 'RoadmapsController', [
        'names' => [
            'index'   => 'roadmaps.index',
            'create'  => 'roadmaps.create',
            'store'   => 'roadmaps.store',
            'show'    => 'roadmaps.show',
            'edit'    => 'roadmaps.edit',
            'update'  => 'roadmaps.update',
            'destroy' => 'roadmaps.destroy',
        ]
    ]);

    Route::group(['prefix' => 'roadmaps', 'as' => 'roadmaps.'], function () {
        Route::resource('{roadmaps}/modules', 'ModuleRoadmapController', [
            'except' => ['show', 'create', 'store'],
            'names'  => [
                'index'   => 'modules.index',
                'edit'    => 'modules.edit',
                'update'  => 'modules.update',
                'destroy' => 'modules.destroy',
            ]
        ]);
    });

    Route::resource('modules', 'ModulesController', [
        'only'  => ['index', 'show', 'create', 'store'],
        'names' => [
            'index'  => 'modules.index',
            'show'   => 'modules.show',
            'create' => 'modules.create',
            'store'  => 'modules.store',
        ],
    ]);

    Route::group(['middleware' => ['admin.module.modify']], function () {
        Route::resource('modules', 'ModulesController', [
            'only'  => ['edit', 'update'],
            'names' => [
                'edit'   => 'modules.edit',
                'update' => 'modules.update',
            ],
        ]);
    });

    Route::delete('modules/{modules}', [
        'middleware' => ['admin.module.destroy'],
        'as'         => 'modules.destroy',
        'uses'       => 'ModulesController@destroy'
    ]);

    Route::group(['prefix' => 'modules', 'as' => 'modules.'], function () {
        Route::group(['middleware' => ['admin.module.modify']], function () {
            Route::resource('{modules}/lessons', 'LessonModuleController', [
                'only'  => ['create', 'store'],
                'names' => [
                    'create' => 'lessons.create',
                    'store'  => 'lessons.store',
                ],
            ]);
        });

        Route::group(['middleware' => ['admin.lesson.modify']], function () {
            Route::resource('{modules}/lessons', 'LessonModuleController', [
                'only'  => ['edit', 'update'],
                'names' => [
                    'edit'   => 'lessons.edit',
                    'update' => 'lessons.update',
                ],
            ]);
        });

        Route::resource('{modules}/lessons', 'LessonModuleController', [
            'only'  => ['index', 'show'],
            'names' => [
                'index' => 'lessons.index',
                'show'  => 'lessons.show',
            ],
        ]);

        Route::group(['middleware' => ['admin.lesson.destroy']], function () {
            Route::resource('{modules}/lessons', 'LessonModuleController', [
                'only'  => ['destroy'],
                'names' => [
                    'destroy' => 'lessons.destroy',
                ],
            ]);
        });
    });

    Route::resource('lessons', 'LessonsController', [
        'only'  => ['index', 'show', 'create', 'store'],
        'names' => [
            'index'  => 'lessons.index',
            'show'   => 'lessons.show',
            'create' => 'lessons.create',
            'store'  => 'lessons.store',
        ],
    ]);

    Route::group(['middleware' => ['admin.lesson.modify']], function () {
        Route::resource('lessons', 'LessonsController', [
            'only'  => ['edit', 'update'],
            'names' => [
                'edit'   => 'lessons.edit',
                'update' => 'lessons.update',
            ],
        ]);
    });

    Route::delete('lessons/{lessons}', [
        'middleware' => ['admin.lesson.destroy'],
        'as'         => 'lessons.destroy',
        'uses'       => 'LessonsController@destroy'
    ]);

    Route::resource('resources', 'ResourcesController', [
        'names' => [
            'index'   => 'resources.index',
            'create'  => 'resources.create',
            'store'   => 'resources.store',
            'show'    => 'resources.show',
            'edit'    => 'resources.edit',
            'update'  => 'resources.update',
            'destroy' => 'resources.destroy',
        ]
    ]);
    Route::post('resources/upload', [
        'as'   => 'resources.upload',
        'uses' => 'ResourcesController@upload'
    ]);

    Route::resource('tags', 'TagsController', [
        'names' => [
            'index'   => 'tags.index',
            'create'  => 'tags.create',
            'store'   => 'tags.store',
            'show'    => 'tags.show',
            'edit'    => 'tags.edit',
            'update'  => 'tags.update',
            'destroy' => 'tags.destroy',
        ]
    ]);

    Route::get('/', ['as' => 'home.index', 'uses' => 'HomeController@index']);
});

Route::group([
    'middleware' => [
        //'auth.joomla',
        //'app.auth',
        //'ACL'
    ],
], function () {
    Route::get('', [
        'uses' => 'RoadmapsController@index'
    ]);

    Route::resource('roadmaps', 'RoadmapsController', [
        'only'  => ['index', 'show'],
        'names' => [
            'index' => 'roadmaps.index',
            'show'  => 'roadmaps.show',
        ]
    ]);
    Route::group(['prefix' => 'roadmaps', 'as' => 'roadmaps.'], function () {
        Route::resource('{roadmaps}/lessons', 'Roadmaps\LessonsController', [
            'only'  => ['index', 'show'],
            'names' => [
                'index' => 'lessons.index',
                'show'  => 'lessons.show',
            ]
        ]);

        Route::post('{roadmaps}/lessons/{lessons}/complete',
            ['as' => 'lessons.complete', 'uses' => 'Roadmaps\LessonsController@complete']);
        Route::post('{roadmaps}/lessons/{lessons}/share',
            ['as' => 'lessons.share', 'uses' => 'Roadmaps\LessonsController@share']);
    });

    Route::resource('tags', 'TagsController', [
        'only'  => ['index', 'show'],
        'names' => [
            'index' => 'tags.index',
            'show'  => 'tags.show',
        ]
    ]);

    Route::resource('modules', 'ModulesController', [
        'only'  => ['index'],
        'names' => [
            'index' => 'modules.index'
        ]
    ]);
    Route::resource('lessons', 'LessonsController', [
        'only'  => ['index', 'show'],
        'names' => [
            'index' => 'lessons.index',
            'show' => 'lessons.show'
        ]
    ]);
    Route::resource('resources', 'ResourcesController', [
        'only'  => ['index'],
        'names' => [
            'index' => 'resources.index'
        ]
    ]);
});

app/Models/User.php
<?php

namespace App\Models;

use Cache;
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, AuthorizableContract, CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword, RoleTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['first_name', 'last_name', 'email'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    public function admin()
    {
        return $this->hasOne(Admin::class, 'id');
    }

    public function author()
    {
        return $this->hasOne(Author::class, 'id');
    }

    public function principal()
    {
        return $this->hasOne(Principal::class, 'id');
    }

    public function groups()
    {
        return $this->belongsToMany(Group::class)->withTimestamps();
    }

    public function isOwner($model)
    {
        $isOwner = false;

        if (is_a($model, Module::class) || is_a($model, Lesson::class)) {
            $isOwner = $this->id == $model->author_id;
        }

        return $isOwner;
    }

    public function getNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function isAdmin()
    {
        return Cache::remember('user.isAdmin', \Config::get('cache.ttl'), function () {
            $hasRecordAdmin = Cache::remember('user.hasRecordAdmin', \Config::get('cache.ttl'), function () {
                return !!$this->admin;
            });

            $hasRoleAdmin = Cache::remember('user.hasRoleAdmin', \Config::get('cache.ttl'), function () {
                return $this->hasRole(Role::ADMIN_NAME);
            });

            return !!($hasRoleAdmin && $hasRecordAdmin);
        });
    }

    public function isAuthor()
    {
        return Cache::remember('user.isAuthor', \Config::get('cache.ttl'), function () {
            $hasRecordAuthor = Cache::remember('user.hasRecordAuthor', \Config::get('cache.ttl'), function () {
                return !!$this->author;
            });

            $hasRoleAuthor = Cache::remember('user.hasRoleAuthor', \Config::get('cache.ttl'), function () {
                return $this->hasRole(Role::AUTHOR_NAME);
            });

            return !!($hasRoleAuthor && $hasRecordAuthor);
        });
    }

    public function isPrincipal()
    {
        return Cache::remember('user.isPrincipal', \Config::get('cache.ttl'), function () {
            $hasRecordPrincipal = Cache::remember('user.hasRecordPrincipal', \Config::get('cache.ttl'), function () {
                return !!$this->principal;
            });

            $hasRolePrincipal = Cache::remember('user.hasRolePrincipal', \Config::get('cache.ttl'), function () {
                return $this->hasRole(Role::PRINCIPAL_NAME);
            });

            return !!($hasRolePrincipal && $hasRecordPrincipal);
        });
    }

    public function getAvatarImages()
    {
        //$images = new Collection();
        $response = false;
        try {
            $response = json_decode(file_get_contents(env('JOOMLA_BRIDGE') . '?userInfo='.$this->id ));
        } catch (\Exception $e) {
            $response = $e;
        }

        return $response;
    }
}

app/Http/Controllers/Admin/ModulesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use App\Models\Author;
use App\Models\Module;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\ModuleStoreRequest;
use App\Http\Requests\Admin\ModuleUpdateRequest;

class ModulesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function index()
    {
        //$modules = Module::with(['authors.user', 'author.user', 'lessons'])->orderBy('created_at', 'desc')->paginate();
        $modules = Module::with(['authors.user', 'author.user', 'lessons'])->orderBy('created_at', 'desc')->get();
        
        return \View::make('admin.modules.index', compact('roadmap', 'modules'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $module = new Module();

        $authors          = Author::get()->lists('name', 'uuid');
        $selected_author  = null;
        $selected_authors = [];
        $leaders          = Module::getAvailableLeaders()->lists('name', 'joomla_user_id');
        $selected_leader  = null;

        return \View::make('admin.modules.create',
            compact('module', 'authors', 'selected_author', 'selected_authors', 'leaders', 'selected_leader'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ModuleStoreRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ModuleStoreRequest $request)
    {
        $module = new Module($request->all());

        $user = \Auth::user();
        if ($user->isAdmin()) {
            $author = User::whereUuid($request->author)->first()->author;
        } else {
            $author = $user->author;
        }

        $module->author()->associate($author);
        $module->save();
        $module->authors()->sync(User::whereIn('uuid', $request->get('authors'))->get());

        return \Redirect::route('admin.modules.index');
    }

    /**
     * Display the specified resource.
     *
     * @param Module $module
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function show(Module $module)
    {
        
        return \Redirect::route('admin.modules.lessons.index', compact('module'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Module $module
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Module $module)
    {
        $authors          = Author::get();
        $authors          = array_combine($authors->pluck('uuid')->toArray(), $authors->pluck('name')->toArray());
        $selected_author  = $module->author->uuid;
        $selected_authors = $module->authors->pluck('uuid')->toArray();

        // Todo: Get leaders correctly
        $leaders         = Module::getAvailableLeaders()->lists('name', 'joomla_user_id');
        $selected_leader = null;

        return \View::make('admin.modules.edit',
            compact('module', 'authors', 'selected_author', 'selected_authors', 'leaders', 'selected_leader'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ModuleUpdateRequest $request
     * @param Module              $module
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(ModuleUpdateRequest $request, Module $module)
    {
        $module->fill($request->all());

        if (\Auth::user()->isAdmin()) {
            $author = User::whereUuid($request->author)->first()->author;
            $module->author()->associate($author);
        }

        $module->save();
        $module->authors()->sync(User::whereIn('uuid', $request->get('authors'))->get());

        return \Redirect::route('admin.modules.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Module $module
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Module $module)
    {
        $module->delete();

        return \Redirect::route('admin.modules.index');
    }
}

app/Http/Controllers/ModulesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Module;

class ModulesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $modules = Module::with('roadmaps')->get();

        return \View::make('modules.index', compact('modules'));
    }

}

resources/views/admin/modules/create.blade.php
@extends('admin.modules.layout')

@section('body')

@include('admin.includes.sidebar')
    <!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">

        <h3>New module</h3>
        <p></p>
        <br>
        @include('admin.modules.form', ['route_name' => 'admin.modules.store', 'method' => 'POST'])
    </section>
</div>
@endsection

resources/views/admin/modules/edit.blade.php
@extends('admin.modules.layout')

@section('body')

@include('admin.includes.sidebar')
    <!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h3>Edit module</h3>
        <p></p>
        <br>
        @include('admin.modules.form', ['route_name' => 'admin.modules.update', 'method' => 'PUT'])
    </section>

    <div class="modal fade modal-dialog-center" id="modal-remove" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content-wrap">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">
                            By deleting this module, every lesson and any record of every principal that did it totally
                            or partially will be deleted as well.
                        </h4>
                    </div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete this module?</p>
                    </div>
                    <div class="modal-footer">
                        {!! Form::open(['route' => ['admin.modules.destroy', $module] ,'method'=>'DELETE', 'data-pjax' => '']) !!}
                        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                        <button type="submit" class="btn btn-danger">Yes</button>{!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/modules/form.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
{!! Form::model($module, ['method' => $method, 'route' => [$route_name, $module], 'data-pjax' => '']) !!}
<div id="" class="box box-primary collapse in">
    <div class="box-body">
        @if(\Auth::user()->isAdmin())
            <div class="form-group">
                {!! Form::label('author', 'Author in charge') !!}
                {!! Form::select('author', $authors, $selected_author, [
                    'placeholder' => trans('module.fields.placeholder.author'),
                    'class' => 'form-control select2'
                ]) !!}
            </div>
        @endif
        <div class="form-group">
            {!! Form::label('authors', 'Authors that can modify') !!}
            {!! Form::select('authors[]', $authors, $selected_authors, [
                'placeholder' => trans('module.fields.placeholder.authors'),
                'id' => 'authors',
                'class' => 'form-control select2',
                'multiple' => '',
            ]) !!}
        </div>
        <div class="form-group">
            {!! Form::label('Leader', 'Leader for module') !!}
            {!! Form::select('joomla_user_id', $leaders, $selected_leader, [
                'placeholder' => trans('module.fields.placeholder.leader'),
                'id' => 'leader',
                'class' => 'form-control select2',
            ]) !!}
        </div>
        <div class="form-group">
            {!! Form::label('discussion_link') !!}
            {!! Form::text('discussion_link', null, ['placeholder' => trans('module.fields.placeholders.discussion_link'), 'class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('title') !!}
            {!! Form::text('title', null, ['placeholder' => trans('module.fields.placeholders.title'), 'class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('description') !!}
            {!! Form::textarea('description', null, ['placeholder' => trans('module.fields.placeholders.description'), 'class' => 'form-control']) !!}
        </div>
        
    </div>
    <div class="box-footer text-right">
        {!! Html::linkRoute('admin.modules.index', 'Back to list', [], ['class' => 'btn btn-default pjax-requester']) !!}
        {!! Form::submit('Save', ['class' => 'btn btn-success', 'data-pjax' => '']) !!}
        @if($route_name === 'admin.modules.update')
            @can('destroy', $module)
            {!! Html::link('#', 'Delete', ['class' => 'btn btn-danger pjax-requester', 'data-toggle' => 'modal', 'data-target' => '#modal-remove']) !!}
            @endcan
        @endif
    </div>
</div>
{!! Form::close() !!}

resources/views/admin/modules/index.blade.php
@extends('admin.modules.layout')

@section('body')

@include('admin.includes.sidebar')
    <!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">

        <h3>Modules</h3>
        <p><small>Create, edit and delete roadmap's modules. Add and edit lessons within a module</small></p>
        <br>

        <div class="box box-primary collapse in" >
            <div class="box-header">
                <div>
                    <a href="{{ URL::route('admin.modules.create') }}" class="btn btn-app pjax-requester">
                        <i class="fa fa-plus"></i> New module
                    </a>
                </div>
            </div>
            <div class="box-body">
                @include('admin.modules.table')
            </div>
        </div>
    </section>
</div>
@endsection

resources/views/admin/modules/layout.blade.php
@extends('admin.layout')
@section('head')
    @include('admin.modules.includes.head')
@endsection
@section('footer-specific')
    @include('admin.modules.includes.footer')
@endsection

resources/views/admin/modules/table.blade.php
<table id="modules" class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>Created</th>
        <th>Title</th>
        <th>In charge of</th>
        <th>Allowed to modify</th>
        
        <th>Lessons available</th>
        <th width="90">Action</th>
    </tr>
    </thead>
    <tbody>

    @forelse($modules as $module)
        <tr>
            <td>{{ $module->created_at }}</td>
            <td>{{ $module->title }}</td>
            <td>{{ $module->author->name }}</td>
            <td>{{ $module->authors->implode('name', ', ') }}</td>
            
            <td>{{ $module->lessons->count() }}</td>
            <td class="action">
                <a href="{{ URL::route('admin.modules.show', $module) }}" title="Show module details and lessons">
                    <span class="fa fa-sitemap" aria-hidden="true"></span>
                </a>
                @can('modify', $module)
                <a href="{{ URL::route('admin.modules.edit', $module) }}" title="Edit module" class="pjax-requester">
                    <span class="fa  fa-edit" aria-hidden="true"></span>
                </a>
                @endcan
                @can('destroy', $module)
                {!! Form::open(['route' => ['admin.modules.destroy', $module] ,'method'=>'DELETE','class'=>'del-form', 'data-pjax' => '']) !!}
                {!! Form::submit('X', ['class' => 'btn-remove link', 'title' => 'Delete module', 'aria-hidden' => 'true']) !!}
                {!! Form::close() !!}
                @endcan
            </td>
        </tr>
    @empty
        <p class="text-center"><i>There are no modules set for this roadmap</i></p>
    @endforelse
    </tbody>
</table>
<div> &nbsp; </div>
{{-- $modules->render(new App\Pagination\AdminLTETwoPresenter($modules)) --}}