app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group([
    //'domain'     => Config::get('app.domain'),
    'namespace'  => 'Admin',
    'as'         => 'admin.',
    'middleware' => [
        'auth.joomla',
        //'admin.auth',
        'ACL',
    ],
    'prefix'     => 'admin'
], function () {
    Route::resource('roadmaps', 'RoadmapsController', [
        'names' => [
            'index'   => 'roadmaps.index',
            'create'  => 'roadmaps.create',
            'store'   => 'roadmaps.store',
            'show'    => 'roadmaps.show',
            'edit'    => 'roadmaps.edit',
            'update'  => 'roadmaps.update',
            'destroy' => 'roadmaps.destroy',
        ]
    ]);

    Route::group(['prefix' => 'roadmaps', 'as' => 'roadmaps.'], function () {
        Route::resource('{roadmaps}/modules', 'ModuleRoadmapController', [
            'except' => ['show', 'create', 'store'],
            'names'  => [
                'index'   => 'modules.index',
                'edit'    => 'modules.edit',
                'update'  => 'modules.update',
                'destroy' => 'modules.destroy',
            ]
        ]);
    });

    Route::resource('modules', 'ModulesController', [
        'only'  => ['index', 'show', 'create', 'store'],
        'names' => [
            'index'  => 'modules.index',
            'show'   => 'modules.show',
            'create' => 'modules.create',
            'store'  => 'modules.store',
        ],
    ]);

    Route::group(['middleware' => ['admin.module.modify']], function () {
        Route::resource('modules', 'ModulesController', [
            'only'  => ['edit', 'update'],
            'names' => [
                'edit'   => 'modules.edit',
                'update' => 'modules.update',
            ],
        ]);
    });

    Route::delete('modules/{modules}', [
        'middleware' => ['admin.module.destroy'],
        'as'         => 'modules.destroy',
        'uses'       => 'ModulesController@destroy'
    ]);

    Route::group(['prefix' => 'modules', 'as' => 'modules.'], function () {
        Route::group(['middleware' => ['admin.module.modify']], function () {
            Route::resource('{modules}/lessons', 'LessonModuleController', [
                'only'  => ['create', 'store'],
                'names' => [
                    'create' => 'lessons.create',
                    'store'  => 'lessons.store',
                ],
            ]);
        });

        Route::group(['middleware' => ['admin.lesson.modify']], function () {
            Route::resource('{modules}/lessons', 'LessonModuleController', [
                'only'  => ['edit', 'update'],
                'names' => [
                    'edit'   => 'lessons.edit',
                    'update' => 'lessons.update',
                ],
            ]);
        });

        Route::resource('{modules}/lessons', 'LessonModuleController', [
            'only'  => ['index', 'show'],
            'names' => [
                'index' => 'lessons.index',
                'show'  => 'lessons.show',
            ],
        ]);

        Route::group(['middleware' => ['admin.lesson.destroy']], function () {
            Route::resource('{modules}/lessons', 'LessonModuleController', [
                'only'  => ['destroy'],
                'names' => [
                    'destroy' => 'lessons.destroy',
                ],
            ]);
        });
    });

    Route::resource('lessons', 'LessonsController', [
        'only'  => ['index', 'show', 'create', 'store'],
        'names' => [
            'index'  => 'lessons.index',
            'show'   => 'lessons.show',
            'create' => 'lessons.create',
            'store'  => 'lessons.store',
        ],
    ]);

    Route::group(['middleware' => ['admin.lesson.modify']], function () {
        Route::resource('lessons', 'LessonsController', [
            'only'  => ['edit', 'update'],
            'names' => [
                'edit'   => 'lessons.edit',
                'update' => 'lessons.update',
            ],
        ]);
    });

    Route::delete('lessons/{lessons}', [
        'middleware' => ['admin.lesson.destroy'],
        'as'         => 'lessons.destroy',
        'uses'       => 'LessonsController@destroy'
    ]);

    Route::resource('resources', 'ResourcesController', [
        'names' => [
            'index'   => 'resources.index',
            'create'  => 'resources.create',
            'store'   => 'resources.store',
            'show'    => 'resources.show',
            'edit'    => 'resources.edit',
            'update'  => 'resources.update',
            'destroy' => 'resources.destroy',
        ]
    ]);
    Route::post('resources/upload', [
        'as'   => 'resources.upload',
        'uses' => 'ResourcesController@upload'
    ]);

    Route::resource('tags', 'TagsController', [
        'names' => [
            'index'   => 'tags.index',
            'create'  => 'tags.create',
            'store'   => 'tags.store',
            'show'    => 'tags.show',
            'edit'    => 'tags.edit',
            'update'  => 'tags.update',
            'destroy' => 'tags.destroy',
        ]
    ]);

    Route::get('/', ['as' => 'home.index', 'uses' => 'HomeController@index']);
});

Route::group([
    'middleware' => [
        //'auth.joomla',
        //'app.auth',
        //'ACL'
    ],
], function () {
    Route::get('', [
        'uses' => 'RoadmapsController@index'
    ]);

    Route::resource('roadmaps', 'RoadmapsController', [
        'only'  => ['index', 'show'],
        'names' => [
            'index' => 'roadmaps.index',
            'show'  => 'roadmaps.show',
        ]
    ]);
    Route::group(['prefix' => 'roadmaps', 'as' => 'roadmaps.'], function () {
        Route::resource('{roadmaps}/lessons', 'Roadmaps\LessonsController', [
            'only'  => ['index', 'show'],
            'names' => [
                'index' => 'lessons.index',
                'show'  => 'lessons.show',
            ]
        ]);

        Route::post('{roadmaps}/lessons/{lessons}/complete',
            ['as' => 'lessons.complete', 'uses' => 'Roadmaps\LessonsController@complete']);
        Route::post('{roadmaps}/lessons/{lessons}/share',
            ['as' => 'lessons.share', 'uses' => 'Roadmaps\LessonsController@share']);
    });

    Route::resource('tags', 'TagsController', [
        'only'  => ['index', 'show'],
        'names' => [
            'index' => 'tags.index',
            'show'  => 'tags.show',
        ]
    ]);

    Route::resource('modules', 'ModulesController', [
        'only'  => ['index'],
        'names' => [
            'index' => 'modules.index'
        ]
    ]);
    Route::resource('lessons', 'LessonsController', [
        'only'  => ['index', 'show'],
        'names' => [
            'index' => 'lessons.index',
            'show' => 'lessons.show'
        ]
    ]);
    Route::resource('resources', 'ResourcesController', [
        'only'  => ['index'],
        'names' => [
            'index' => 'resources.index'
        ]
    ]);
});

resources/views/admin/includes/footer.blade.php
<!-- jQuery + bootstrap-->
<script src="{{ asset('/js/app.js') }}"></script>

<!-- AdminLTE App -->
<script src="{{ asset('/js/AdminLTE.min.js') }}"></script>

<!-- AdminLTE Plugins -->
<script src="{{ asset('/js/jquery.slimscroll.min.js') }}"></script>

<!-- jQuery-pjax -->
<script src="{{ asset('/js/jquery.pjax.js') }}"></script>

resources/views/admin/includes/head.blade.php
<meta charset="UTF-8">
<title>VIF PR</title>
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- CSS -->
<link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css">
<link href="http://cc.xeedlabs.com/vendor/bootstrap/dist/css/bootstrap-theme.min.css" rel="stylesheet" type="text/css">
<!-- Select2 -->
<link href="{{ asset('css/select2.min.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('css/AdminLTE.min.css') }}" rel="stylesheet" type="text/css">

<link href="{{ asset('css/AdminLTE.blue.min.css') }}" rel="stylesheet" type="text/css">

<link href="{{ asset('css/roadmap.css') }}" rel="stylesheet" type="text/css">


<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />

<script type="text/javascript">
    if (!admin) {
        var admin = {
            pr: {}
        };
    } else if (!admin.pr) {
        admin.pr = {};
    }

    admin.pr.ver = "0.0.1";
    admin.pr.base_url = "{{url()}}/";
    admin.pr._token = '{{ csrf_token() }}';
</script>

resources/views/admin/includes/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="{{ URL::route('admin.home.index') }}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><i class="fa fa-shield"></i>Pr</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><i class="fa fa-shield"></i> Principal Roadmap</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
    </nav>
</header>

resources/views/admin/includes/sidebar.blade.php
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <div class="user-panel">
        <div class="pull-left image">
          <img src="http://www.sessionlogs.com/media/icons/defaultIcon.png" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p><?=Auth::user()->first_name?> <?=Auth::user()->last_name?></p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li class="header">MAIN NAVIGATION</li>
            <li>
                <a href="/admin/">
                    <i class="fa fa-home"></i> <span>Dashboard</span>
                </a>
            </li>
            @can('admin.roadmaps.index')
            <li class="treeview">
                <a href="{{ URL::route('admin.roadmaps.index') }}">
                    <i class="fa fa-map"></i> <span>Roadmaps</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <a href="{{ URL::route('admin.roadmaps.index') }}">
                            <i class="fa fa-list-alt"></i>List
                        </a>
                    </li>
                    <li>
                        <a href="{{ URL::route('admin.roadmaps.create') }}">
                            <i class="fa fa-plus"></i>New
                        </a>
                    </li>
                </ul>
            </li>
            @endcan
            <li class="treeview">
                <a href="{{ URL::route('admin.modules.index') }}">
                    <i class="fa fa-clone"></i> <span>Modules</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <a href="{{ URL::route('admin.modules.index') }}">
                            <i class="fa fa-list-alt"></i>List
                        </a>
                    </li>
                    <li>
                        <a href="{{ URL::route('admin.modules.create') }}">
                            <i class="fa fa-plus"></i>New
                        </a>
                    </li>
                </ul>
            </li>
            @can('admin.lessons.index')
            <li class="treeview">
                <a href="{{ URL::route('admin.lessons.index') }}">
                    <i class="fa fa-map"></i> <span>Lessons</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <a href="{{ URL::route('admin.lessons.index') }}">
                            <i class="fa fa-list-alt"></i>List
                        </a>
                    </li>
                    <li>
                        <a href="{{ URL::route('admin.lessons.create') }}">
                            <i class="fa fa-plus"></i>New
                        </a>
                    </li>
                </ul>
            </li>
            @endcan
            <li class="treeview">
                <a href="{{ URL::route('admin.resources.index') }}">
                    <i class="fa fa-files-o"></i> <span>Resources</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <a href="{{ URL::route('admin.resources.index') }}">
                            <i class="fa fa-list-alt"></i>List
                        </a>
                    </li>
                    <li>
                        <a href="{{ URL::route('admin.resources.create') }}">
                            <i class="fa fa-plus"></i>New
                        </a>
                    </li>
                </ul>
            </li>
            @can('admin.tags.index')
            <li class="treeview">
                <a href="{{ URL::route('admin.tags.index') }}">
                    <i class="fa fa-tags"></i> <span>Tags</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <a href="{{ URL::route('admin.tags.index') }}">
                            <i class="fa fa-list-alt"></i>List
                        </a>
                    </li>
                    <li>
                        <a href="{{ URL::route('admin.tags.create') }}">
                            <i class="fa fa-plus"></i>New
                        </a>
                    </li>
                </ul>
            </li>
            @endcan
            <li>
                <a href="{{ env('JOOMLA_LOGIN') }}">
                    <i class="fa fa-sign-out"></i> <span>Logout</span>
                </a>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>